#!/bin/sh
### BEGIN INIT INFO
# Provides:          puppetmaster
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: puppetmaster
# Description:       puppetmaster
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

DAEMON=/usr/bin/thin
SCRIPT_NAME=/etc/init.d/puppetmaster
CONFIG=/etc/puppetmaster.yml
PIDDIR=<%= puppet_pid_dir %>

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

if [ "X$2" = X ] || [ "X$3" = X ]; then
    INSTANCES="-C $CONFIG"
fi

rh_status() {
    for PIDFILE in $PIDDIR/puppetmasterd.*.pid
    do
        status -p ${PIDFILE} puppetmaster
    done
}
case "$1" in
  status)
  rh_status
  RETVAL=$?
  ;;
  start)
  $DAEMON start $INSTANCES
  ;;
  stop)
  $DAEMON stop $INSTANCES
  ;;
  restart)
  $DAEMON restart $INSTANCES
  ;;
  *)
  echo "Usage: $SCRIPT_NAME {status|start|stop|restart}" >&2
  exit 3
  ;;
esac

:
